
project_id = "hrrlefgnhkbzuwyklejj"
# For create-delivery-payment
STRIPE_API_KEY = "{{ secrets.STRIPE_SECRET_KEY }}"
WEBHOOK_SECRET = ""

# For Notifications
SUPABASE_URL = "{{ secrets.SUPABASE_URL }}"
SUPABASE_SERVICE_ROLE_KEY = "{{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
SUPABASE_DB_URL = "{{ secrets.SUPABASE_DB_URL }}"

# For email sending
RESEND_API_KEY = "{{ secrets.RESEND_API_KEY }}"
